AWSTemplateFormatVersion: 2010-09-09

Description: >- 
  An AWS Serverless Specification template describing your function.

Transform: 
- AWS::Serverless-2016-10-31

Resources:
  myCovinProxy:
    Type: AWS::Serverless::Function
    Properties:
      Handler: hello.handler
      Runtime: provided.al2
      CodeUri: .
      Description: Covin Proxy
      MemorySize: 128
      Timeout: 3
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref myCovinHttpApi
            Path: /proxy/{proxy+}
            Method: ANY
      Environment:
        Variables:
          BASE_URL: https://cdn-api.co-vin.in/api
          DISTRICTS_URL: https://dashboard.cowin.gov.in/assets/json/csvjson.json
          AWS_COGNITO_REGION: ap-south-1
          AWS_COGNITO_POOL_ID: ap-south-1_0DvxhDRsV
          AWS_COGNITO_APP_CLIENT_ID: 68uau6menju7q3prl3t3gr1ksu
          RUST_LOG: debug
          USER_AGENT_HEADER: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1 Safari/605.1.15
          REFERER_HEADER: https://www.cowin.gov.in/
          ORIGIN_HEADER: https://www.cowin.gov.in
    Metadata:
      BuildMethod: makefile

  myCovinApi:
    Type: AWS::Serverless::Function
    Properties:
      Handler: hello.handler
      Runtime: provided.al2
      CodeUri: .
      Description: Covin Api
      MemorySize: 128
      Timeout: 3
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref myCovinHttpApi
            Path: /api/{proxy+}
            Method: ANY
      Environment:
        Variables:
          BASE_URL: https://cdn-api.co-vin.in/api
          DISTRICTS_URL: https://dashboard.cowin.gov.in/assets/json/csvjson.json
          AWS_COGNITO_REGION: ap-south-1
          AWS_COGNITO_POOL_ID: ap-south-1_0DvxhDRsV
          AWS_COGNITO_APP_CLIENT_ID: 68uau6menju7q3prl3t3gr1ksu
          RUST_LOG: debug
          USER_AGENT_HEADER: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1 Safari/605.1.15
          REFERER_HEADER: https://www.cowin.gov.in/
          ORIGIN_HEADER: https://www.cowin.gov.in
    Metadata:
      BuildMethod: makefile

  myCovinAlertEngine:
    Type: AWS::Serverless::Function
    Properties:
      Handler: hello.handler
      Runtime: provided.al2
      CodeUri: .
      Description: Covin Alert Engine
      MemorySize: 128
      Timeout: 15
      Events:
        FMSchedule:
          Type: Schedule
          Properties:
            Name: FiveMinuteSchedule
            Schedule: 'rate(5 minutes)'
            Description: Run every five minutes schedule
            Enabled: True
      Environment:
        Variables:
          BASE_URL: https://cdn-api.co-vin.in/api
          RUST_LOG: debug
          USER_AGENT_HEADER: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1 Safari/605.1.15
          REFERER_HEADER: https://www.cowin.gov.in/
          ORIGIN_HEADER: https://www.cowin.gov.in 
    Metadata:
      BuildMethod: makefile

  myCovinHttpApi:
    Type: AWS::Serverless::HttpApi
