name: Rust

on:
  push:
    branches: [ main ]
    paths: 
      - "api/*"

  pull_request:
    branches: [ main ]
    paths: 
      - "api/*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: cd api/
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
