name: Rust

on:
  push:
    branches: [ main ]
    paths: 
      - "api/*"
      - ".github/workflows/*"

  pull_request:
    branches: [ main ]
    paths: 
      - "api/*"
      - ".github/workflows/*"

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: api

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
