name: Rust

on:
  push:
    branches: [ main ]
    paths: 
      - "api/*"
      - ".github/workflows/*"

  pull_request:
    branches: [ main ]
    paths: 
      - "api/*"
      - ".github/workflows/*"

env:
  CARGO_TERM_COLOR: always

defaults:
  run:
    working-directory: api

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: aslamplr/lambda-rust
      volumes: 
        - ${{ github.workspace }}:/code
        - /home/github/.cargo/registry:/root/.cargo/registry
        - /home/github/.cargo/git:/root/.cargo/git 
    steps:
      - uses: actions/checkout@v2
      - name: AWS lambda build
        run: /usr/local/bin/build.sh
        env:
          - PROFILE: release
          - PACKAGE: false
      - run: ls -l target/lambda/release
      - name: SAM build
        run: sam build
      - name: SAM deploy
        run: echo "sam deploy not done now"
